


POINTS = {
   'stations_executive_desk': {
      'Installation Difficulty': 'The user found the product installation either difficult or easy.',
      'Installation Time': 'The installation took an unreasonably long time, and the user perceived it as too long. There is a distinction between an objective duration declare and a complaint.',
      'Number of Assembly Parts': 'The user felt there were too many parts to assemble.',
      'Manual Content': 'The instruction manual is comprehensive, easy to understand, and accurate.',
      'Package Integrity': 'The package was intact upon arrival. Damage to internal parts does not imply poor packaging.',
      'Damage upon arrival': 'Some parts of the product itself were damaged upon arrival, or some components were broken.',
      'Missing or Wrong Parts': 'Some items were missing or incorrect in the received product.',
      'Shipping Speed': 'The user received the product within a certain timeframe.',
      'Customer Service Quality': 'The user had a specific experience with customer service when encountering issues after receiving the product.',
      'After-sales return and exchange service': 'The user had a particular experience and incurred costs when requesting a return or exchange due to issues.',
      'Screw Hole Alignment': 'The screws and holes aligned properly or did not align during installation.',
      'Drawer Slide Smoothness': 'The drawer operates smoothly.',
      'Cabinet Door Smoothness': 'The cabinet door opens and closes smoothly.',
      'Noise During Use': 'The product produces noise during use.',
      'Panel Alignment': 'If the table consists of multiple panels, they are properly aligned or misaligned after assembly.',
      'Component quality': 'Some parts are easily damaged during installation or use.',
      'Tabletop Quality': 'The tabletop quality is defined by its material, thickness, hardness, water resistance, and edge finishing.',
      'Table leg quality': 'The table leg quality is defined by its material, slip resistance, and sturdiness.',
      'Stability': 'The table is stable and does not wobble.',
      'Odor': 'The product has or does not have an unpleasant odor.',
      'Ease of Cleaning': 'The table is easy to clean during use.',
      'Stain Resistance': 'The table resists stains over time.',
      'Aesthetics': 'The table is visually appealing, stylish, and elegant.',
      'Color': 'The table has a specific color.',
      'Legroom Space': 'The legroom is spacious enough and does not feel cramped.',
      'Storage Space': 'The user has enough storage space for their items. Desk surface space is not considered storage; only drawers and shelves qualify.',
      'Additional power outlet': 'The product includes power outlets, Type-C ports, USB ports, or similar features.',
      'Cable Management': 'The product has cable management features such as cable holes, organizers, or trays.'
   },
   'wayfair': {
      'Installation Difficulty': 'The user found the product installation either difficult or easy.',
      'Installation Time': 'The installation took an unreasonably long time, and the user perceived it as too long. There is a distinction between an objective duration declare and a complaint.',
      'Number of Assembly Parts': 'The user felt there were too many parts to assemble.',
      'Manual Content': 'The instruction manual is comprehensive, easy to understand, and accurate.',
      'Package Integrity': 'The package was intact upon arrival. Damage to internal parts does not imply poor packaging.',
      'Damage upon arrival': 'Some parts of the product itself were damaged upon arrival, or some components were broken.',
      'Missing or Wrong Parts': 'Some items were missing or incorrect in the received product.',
      'Shipping Speed': 'The user received the product within a certain timeframe.',
      'Customer Service Quality': 'The user had a specific experience with customer service when encountering issues after receiving the product.',
      'After-sales return and exchange service': 'The user had a particular experience and incurred costs when requesting a return or exchange due to issues.',
      'Screw Hole Alignment': 'The screws and holes aligned properly or did not align during installation.',
      'Drawer Slide Smoothness': 'The drawer operates smoothly.',
      'Cabinet Door Smoothness': 'The cabinet door opens and closes smoothly.',
      'Panel Alignment': 'If the table consists of multiple panels, they are properly aligned or misaligned after assembly.',
      'Quality': "The table's quality.",
      'Component quality': 'Some parts are easily damaged during installation or use.',
      'Tabletop Quality': 'The tabletop quality is defined by its material, thickness, hardness, water resistance, and edge finishing.',
      'Table leg quality': 'The table leg quality is defined by its material, slip resistance, and sturdiness.',
      'Sturdiness': 'The table is solid.',
      'Odor': 'The product has or does not have an unpleasant odor.',
      'Ease of Cleaning': 'The table is easy to clean during use.',
      'Desktop Edge Processing': 'Smooth finish on all edges and surfaces – minor scratches or paint wear are not related to smoothness.',
      'Stain Resistance': 'The table resists stains over time.',
      'Aesthetics': 'The table is visually appealing, stylish, and elegant.',
      'Color': 'The table has a specific color.',
      'Legroom Space': 'The legroom is spacious enough and does not feel cramped.',
      'Storage Space': 'The user has enough storage space for their items. Desk surface space is not considered storage; only drawers and shelves qualify.',
      'Additional power outlet': 'The product includes power outlets, Type-C ports, USB ports, or similar features.',
      'Cable Management': 'The product has cable management features such as cable holes, organizers, or trays.',
      'Space and Size': 'The product is suit for the room. Desk surface space is consider.',
      'Craftsmanship': 'The product is well-made.',
      'Price': 'The price is worth buying and not  expensive',
      'Product Description': 'The product is as described.'
   },
   'standing_desk': {
      'Assembly difficulty & Time': 'Installation Difficulty and Time Requirement',
      'Instruction Quality': 'Manual Quality, Including Clarity',
      'Customizability': 'Flexibility for Personal Customization (e.g., Modifying Legs, Adding Accessories, Upgrading Electrical Components)',
      'Number of Assembly Parts': 'Number of Parts Required for Assembly',
      'Appearance & Style': 'visual characteristics and aesthetic presentation',
      'Color': 'The color of desk',
      'Multi-Board Desktop': 'Made of multiple wooden boards, which may cause unevenness or imperfections in appearance.',
      'Stability & Sturdiness': 'the ability to remain steady and balanced, being strong and durable',
      'Maximum Height': "Whether the maximum height meet the user's requirements.",
      'Height adjustment smoothness': 'Smoothness During Height Adjustment (Equivalent to Motor Smoothness)',
      'Height adjustment speed': 'Speed of Height Adjustment',
      'Noise Level': 'Noise level during using (mostly by motor noise)',
      'preset heights function': 'allows users to save and quickly access specific height',
      'Anti-Collision Sensitivity': 'Collision Detection and Rebound Sensitivity',
      'Modularity': 'modules can be easily assembled or modified',
      'Lighting Feature': 'provides illumination, enhancing visibility, atmosphere (e.g., LED Lighting)',
      'Integrated Power and Charging Ports': 'built-in connectors that allow for convenient power',
      'Storage Features': 'Overall Storage Functionality (Excluding Desktop Size; Focus on Drawers and Shelving)',
      'Mobility': 'the ability to be moved easily and freely',
      'Keyboard Tray': 'Keyboard Tray',
      'Product Reliability': 'Product Reliability, Including Durability',
      'Water Resistance': 'product can prevent water from penetrating its surface',
      'Desktop Quality': 'Including Thickness and Material',
      'Hardware Quality': 'Quality of Parts Such as Screws and Small Metal Components',
      'Drawers Quality': 'Drawer Quality, Including Smoothness and Durability',
      'Pilot Holes Alignment': 'Alignment Accuracy of Pre-drilled Holes',
      'Odor': 'whether desk is smelly',
      'ergonomic': 'Comfort and Ergonomic Support During Sit-Stand Transition (Including Health Benefits)',
      'Value for Money': 'what customers spend is worth what their receive',
      'Shipping Speed': 'Shipping Speed',
      'Packaging Quality': 'The package was intact upon arrival. Damage to internal parts does not imply poor packaging.',
      'Product Integrity': 'Upon arrival, the completeness of product, including parts and accessories, and any damage or dedects.',
      'customer service': 'Customer service quality, including response speed and response quality',
      'After-sales Service': 'Missing Part Replacement, etc.',
      'Return Experience': 'overall satisfaction a customer has when returning a product',
      'Cable management': 'cable management features such as cable holes, organizers, or trays.',
      'Desktop Size': 'Desktop spaciousness and adequacy of workspace',
      'Desk Shape': 'desk shape, including L-shape, U-shape, etc.',
      'Load capacity': 'maximum weight or force that product can safely support',
      'Recommendation': 'Willingness to Recommend to Others',
      'product image/description mismatch': 'The received product is different from the product image or description.'
   },
   'banshi_desk': {
      'Assembly difficulty & Time': 'Installation Difficulty and Time Requirement',
      'Instruction Quality': 'Manual Quality, Including Clarity',
      'Number of Assembly Parts': 'Number of Parts Required for Assembly',
      'Part Identifiability': 'Whether the components and accessories of a product are easily recognizable',
      'Integrated Power and Charging Ports': 'built-in connectors that allow for convenient power',
      'Storage Features': 'Overall Storage Functionality (Excluding Desktop Size; Focus on Drawers and Shelving)',
      'Keyboard Tray': 'Keyboard Tray',
      'PC Tower Space': 'Space for storing a PC tower',
      'Leg Room': 'The space available for the user to stretch or place their legs',
      'Appearance & Style': 'visual characteristics and aesthetic presentation',
      'Color': 'The color of desk',
      'Stability & Sturdiness': 'Stability and Sturdiness',
      'Product Reliability': 'Product Reliability, Including Durability',
      'Water Resistance': 'product can prevent water from penetrating its surface',
      'Desktop Quality': 'Including thickness and material',
      'Hardware Quality': 'Quality of Parts Such as Screws and Small Metal Components',
      'Drawers Quality': 'Drawer Quality, Including Smoothness and Durability',
      'Pilot Holes Alignment': 'Alignment Accuracy of Pre-drilled Holes',
      'Odor': 'whether desk is smelly',
      'Value for money': 'what customers spend is worth what their receive',
      'Shipping Speed': 'Shipping Speed',
      'packaging quality': 'The package was intact upon arrival. Damage to internal parts does not imply poor packaging.',
      'Product Integrity': 'Upon arrival, the completeness of product, including parts and accessories, and any damage or dedects.',
      'customer service': 'Customer service quality, including response speed and response quality',
      'After-sales Service': 'Missing Part Replacement, etc.',
      'Return Experience': 'overall satisfaction a customer has when returning a product',
      'Cable management': 'cable management features such as cable holes, organizers, or trays.',
      'Desktop Size': 'Desktop spaciousness and adequacy of workspace',
      'Desk Shape': 'desk shape, including L-shape, U-shape, etc.',
      'Load capacity': 'maximum weight or force that product can safely support',
      'Recommendation': 'Willingness to Recommend to Others',
      'product image/description mismatch': 'The received product is different from the product image or description.'
   },
   'gangmu_desk': {
      'Assembly difficulty & Time': 'Installation Difficulty and Time Requirement',
      'Instruction Quality': 'Manual Quality, Including Clarity',
      'Number of Assembly Parts': 'Number of Parts Required for Assembly',
      'Configurability': 'Can change the shape or direction of desk',
      'Part Identifiability': 'Whether the components and accessories of a product are easily recognizable',
      'Lighting Feature': 'provides illumination, enhancing visibility, atmosphere (e.g., LED Lighting)',
      'Integrated Power and Charging Ports': 'built-in connectors that allow for convenient power',
      'Storage Features': 'Overall Storage Functionality (Excluding Desktop Size; Focus on Drawers and Shelving)',
      'PC Tower Space': 'Space for storing a PC tower',
      'Keyboard Tray': 'Keyboard Tray',
      'Shelf Space': 'Including shelf capacity, quality, and stability',
      'Pegboard Feature': 'Whether Pegboard Feature Good',
      'Leg Room': 'The space available for the user to stretch or place their legs',
      'Suitability for Gaming': 'Compatibility with gaming scenarios',
      'Appearance & Style': 'visual characteristics and aesthetic presentation',
      'Color': 'Color or desk',
      'Multi-Board Desktop': 'Made of multiple wooden boards, which may cause unevenness or imperfections in appearance.',
      'Stability & Sturdiness': 'Stability and Sturdiness',
      'Product Reliability': 'Product Reliability, Including Durability',
      'Water Resistance': 'product can prevent water from penetrating its surface',
      'Desktop Quality': 'Including thickness and material',
      'Hardware Quality': 'Quality of Parts Such as Screws and Small Metal Components',
      'Drawers Quality': 'Drawer Quality, Including Smoothness and Durability',
      'Pilot Holes Alignment': 'Alignment Accuracy of Pre-drilled Holes',
      'Odor': 'whether desk is smelly',
      'Value for money': 'what customers spend is worth what their receive',
      'Shipping Speed': 'Shipping Speed',
      'packaging quality': 'The package was intact upon arrival. Damage to internal parts does not imply poor packaging.',
      'Product Integrity': 'Upon arrival, the completeness of product, including parts and accessories, and any damage or dedects.',
      'customer service': 'Customer service quality, including response speed and response quality',
      'After-sales Service': 'Missing Part Replacement, etc.',
      'Return Experience': 'overall satisfaction a customer has when returning a product',
      'Cable management': 'cable management features such as cable holes, organizers, or trays.',
      'Desktop Size': 'Desktop spaciousness and adequacy of workspace',
      'Desk Shape': 'desk shape, including L-shape, U-shape, etc.',
      'Load capacity': 'maximum weight or force that product can safely support',
      'Recommendation': 'Willingness to Recommend to Others',
      'product image/description mismatch': 'The received product is different from the product image or description.'
   },
   'ceiling_fan': {
      'Cord & Wire Management': 'How well the product handles cables and wiring',
      'Product Size': 'The physical dimensions of the product',
      'Timer Function': 'The ability to set a countdown or scheduled on/off time',
      'Product Weight': 'How heavy or light the product feels',
      'Airflow Performance': 'Fan airflow and wind speed performance at different settings',
      'Stability & Sturdiness': 'Fan stability and wobble during operation',
      'Remote & Control Functions': 'Features related to remote access or control',
      'Noise Level': 'How loud or quiet the product operates',
      'Reverse Function': 'The ability to reverse airflow direction',
      'High-Speed Performance': 'How well the product performs when operating at high-speed, including stability and airflow strength',
      'Low-Speed Performance': 'How well the product performs when operating at low-speed, including airflow strength',
      'Energy Efficiency': 'how cost-effective and eco-friendly the product is',
      'Brightness': 'The intensity of the light output',
      'Light Color': 'The hue or temperature of the emitted light',
      'Lighting Control': 'Features that allow adjustment of lighting, such as dimming, color changing, or scheduling.',
      'Smart Home Integration': 'Compatibility with smart home systems like Alexa etc.',
      'Large Space & Outdoor Suitability': 'Whether the product is appropriate for use in big rooms or outside environments.',
      'Installation Difficulty': 'Including Installation difficulty, technical requirements, and time consumption',
      'Manual Quality': 'The clarity, completeness, and usefulness of the instruction manual.',
      'Configuration Difficulty': 'Ease of WiFi connection, app pairing, and initial configuration (including airflow and lighting settings)',
      'Style & Appearance': 'Fan and lighting appearance, style, and visual aesthetics',
      'Product Color': 'The color of product',
      'Product Reliability': 'Overall product quality and durability',
      'Blade Quality': 'Fan blade quality, stability, and durability',
      'Downrod Quality': 'Downrod length, adjustability, and quality',
      'Water Resistance': 'Water resistance, including rust prevention',
      'Maintenance & Cleaning': 'Ease of daily cleaning and maintenance',
      'Hardware Quality': 'Quality of hardware parts such as screws and small metal components',
      'Price & Value': 'Comparison of fan price versus performance and features (price-to-value)',
      'Shipping Speed': 'How quickly the product arrives after ordering.',
      'Packaging Quality': 'The condition and protection level of the box and internal packaging materials.',
      'Product Integrity': 'Product completeness upon arrival, including all parts and accessories',
      'Customer Service': 'Customer service quality, including response speed and helpfulness',
      'After-Sales Service': 'After-sales service, including missing part replacement',
      'Return & Exchange Experience': 'How smooth and hassle-free the process was for returning',
      'Recommendation': 'Willingness to recommend to others'
   },
}