


POINTS = {
    'stations': {'Installation Difficulty': 'The user found the product installation either difficult or easy.',
 'Installation Time': 'The installation took an unreasonably long time, and the user perceived it as too long. There is a distinction between an objective duration declare and a complaint.',
 'Number of Assembly Parts': 'The user felt there were too many parts to assemble.',
 'Manual Content': 'The instruction manual is comprehensive, easy to understand, and accurate.',
 'Package Integrity': 'The package was intact upon arrival. Damage to internal parts does not imply poor packaging.',
 'Damage upon arrival': 'Some parts of the product itself were damaged upon arrival, or some components were broken.',
 'Missing or Wrong Parts': 'Some items were missing or incorrect in the received product.',
 'Shipping Speed': 'The user received the product within a certain timeframe.',
 'Customer Service Quality': 'The user had a specific experience with customer service when encountering issues after receiving the product.',
 'After-sales return and exchange service': 'The user had a particular experience and incurred costs when requesting a return or exchange due to issues.',
 'Screw Hole Alignment': 'The screws and holes aligned properly or did not align during installation.',
 'Drawer Slide Smoothness': 'The drawer operates smoothly.',
 'Cabinet Door Smoothness': 'The cabinet door opens and closes smoothly.',
 'Noise During Use': 'The product produces noise during use.',
 'Panel Alignment': 'If the table consists of multiple panels, they are properly aligned or misaligned after assembly.',
 'Component quality': 'Some parts are easily damaged during installation or use.',
 'Tabletop Quality': 'The tabletop quality is defined by its material, thickness, hardness, water resistance, and edge finishing.',
 'Table leg quality': 'The table leg quality is defined by its material, slip resistance, and sturdiness.',
 'Stability': 'The table is stable and does not wobble.',
 'Odor': 'The product has or does not have an unpleasant odor.',
 'Ease of Cleaning': 'The table is easy to clean during use.',
 'Stain Resistance': 'The table resists stains over time.',
 'Aesthetics': 'The table is visually appealing, stylish, and elegant.',
 'Color': 'The table has a specific color.',
 'Legroom Space': 'The legroom is spacious enough and does not feel cramped.',
 'Storage Space': 'The user has enough storage space for their items. Desk surface space is not considered storage; only drawers and shelves qualify.',
 'Additional power outlet': 'The product includes power outlets, Type-C ports, USB ports, or similar features.',
 'Cable Management': 'The product has cable management features such as cable holes, organizers, or trays.'},

    'wayfair': {'Installation Difficulty': 'The user found the product installation either difficult or easy.',
 'Installation Time': 'The installation took an unreasonably long time, and the user perceived it as too long. There is a distinction between an objective duration declare and a complaint.',
 'Number of Assembly Parts': 'The user felt there were too many parts to assemble.',
 'Manual Content': 'The instruction manual is comprehensive, easy to understand, and accurate.',
 'Package Integrity': 'The package was intact upon arrival. Damage to internal parts does not imply poor packaging.',
 'Damage upon arrival': 'Some parts of the product itself were damaged upon arrival, or some components were broken.',
 'Missing or Wrong Parts': 'Some items were missing or incorrect in the received product.',
 'Shipping Speed': 'The user received the product within a certain timeframe.',
 'Customer Service Quality': 'The user had a specific experience with customer service when encountering issues after receiving the product.',
 'After-sales return and exchange service': 'The user had a particular experience and incurred costs when requesting a return or exchange due to issues.',
 'Screw Hole Alignment': 'The screws and holes aligned properly or did not align during installation.',
 'Drawer Slide Smoothness': 'The drawer operates smoothly.',
 'Cabinet Door Smoothness': 'The cabinet door opens and closes smoothly.',
 'Panel Alignment': 'If the table consists of multiple panels, they are properly aligned or misaligned after assembly.',
 'Quality': "The table's quality.",
 'Component quality': 'Some parts are easily damaged during installation or use.',
 'Tabletop Quality': 'The tabletop quality is defined by its material, thickness, hardness, water resistance, and edge finishing.',
 'Table leg quality': 'The table leg quality is defined by its material, slip resistance, and sturdiness.',
 'Sturdiness': 'The table is solid.',
 'Odor': 'The product has or does not have an unpleasant odor.',
 'Ease of Cleaning': 'The table is easy to clean during use.',
 'Desktop Edge Processing': 'Smooth finish on all edges and surfaces – minor scratches or paint wear are not related to smoothness.',
 'Stain Resistance': 'The table resists stains over time.',
 'Aesthetics': 'The table is visually appealing, stylish, and elegant.',
 'Color': 'The table has a specific color.',
 'Legroom Space': 'The legroom is spacious enough and does not feel cramped.',
 'Storage Space': 'The user has enough storage space for their items. Desk surface space is not considered storage; only drawers and shelves qualify.',
 'Additional power outlet': 'The product includes power outlets, Type-C ports, USB ports, or similar features.',
 'Cable Management': 'The product has cable management features such as cable holes, organizers, or trays.',
 'Space and Size': 'The product is suit for the room. Desk surface space is consider.',
 'Craftsmanship': 'The product is well-made.',
 'Price': 'The price is worth buying and not  expensive',
 'Product Description': 'The product is as described.'}
 }